default_install_hook_types: [pre-commit, commit-msg]
repos:
  - repo: https://github.com/jeremiah-c-leary/vhdl-style-guide
    rev: 3.30.0
    hooks:
      - id: vsg
        args: ["--configuration=./.vhdl-style.yaml"]
        exclude: ^Ethernet/xilinx/sFPDP
  - repo: local
    hooks:
      - id: verible
        name: Verible
        args: ["--column_limit=120", "--inplace"]
        types: ["text"]
        files: '.*\.(v|vh|sv|svh)'
        entry: verible-verilog-format
        language: system
        stages: [pre-commit]
